global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: node-exporter
   static_configs:
     - targets:
        - "node-exporter:9100"
 - job_name: go-prom-metrics
   static_configs:
     - targets:
        - "go-prom-metrics:2112"