apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: alert-manager
  name: alert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alert-manager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/prometheus-loki-grafana-go-localprom: "true"
        io.kompose.service: alert-manager
    spec:
      containers:
        - name: alert-manager
          image: prom/alertmanager
          ports:
            - containerPort: 9093
              hostPort: 9093
              protocol: TCP
          volumeMounts:
            - mountPath: /alertmanager/alertmanager.yml
              name: alert-manager-cm
              subPath: alertmanager.yml
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
            name: alert-manager-cm
          name: alert-manager-cm
