apiVersion: v1
kind: ConfigMap
data:
  alertmanager.yml: |-
    global:
      smtp_smarthost: 'smtp:25'
      smtp_from: 'email@example.com'
    route:
      receiver: example-email
      group_by: [alertname]
    receivers:
     - name: example-email
       email_configs:
        - to: 'email@example.com'
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: alert-manager
  name: alert-manager-cm
