apiVersion: v1
kind: ConfigMap
data:
  promtail-config.yml: |-
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki:3100/loki/api/v1/push

    scrape_configs:          
    - job_name: go-prom-metrics
      static_configs:
      - targets:
          - localhost
        labels:
          app: go-prom-metrics
          __path__: /var/log/go-prom-metrics.log
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: promtail
  name: go-prom-metrics-cm
